[package]
edition = "2021"
name = "aviate"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[features]
dev = []

[dependencies]
gdal = {version = "0.17", features = ["bindgen"]}
godot = {version = "0.2", features = ["experimental-threads"]}
rstar = "0.12"

[profile.release]
strip = "symbols"
