[package]
authors = ["Barugon"]
description = "VFR Flight Planner"
edition = "2021"
license = "GPL-3.0-or-later"
name = "fp_app"
version = "0.1.0"

[features]
phosh = []

[dependencies]
dirs = "5.0"
eframe = "0.23"
egui_extras = {version = "0.23", features = ["image"]}
egui_file = "0.11"
gdal = "0.16"
image = {version = "0.24", features = ["png"]}
rstar = "0.11"
serde_json = "1.0"

[profile.release]
strip = "symbols"

[profile.dev]
# opt-level = 1
