[package]
authors = ["Barugon"]
description = "VFR Flight Planner"
edition = "2021"
license = "GPL-3.0-or-later"
name = "fp_app"
version = "0.1.0"

[features]
phosh = []

[dependencies]
dirs = "5.0"
eframe = {git = "https://github.com/Barugon/egui.git", branch = "combined_changes", default-features = false, features = ["accesskit", "default_fonts", "wgpu"]}
egui_extras = {git = "https://github.com/Barugon/egui.git", branch = "combined_changes", features = ["image"]}
egui_file = {git = "https://github.com/Barugon/egui_file.git", branch = "local_egui"}
gdal = {git = "https://github.com/georust/gdal.git"}
image = {version = "0.24", features = ["png"]}
rstar = "0.11"
serde_json = "1.0"

[profile.release]
strip = "symbols"

[profile.dev]
# opt-level = 1
