[package]
authors = ["Barugon"]
description = "VFR Flight Planner"
edition = "2021"
name = "fp_app"
version = "0.1.0"

[dependencies]
dirs = "4.0"
eframe = {path = "../egui/eframe", features = ["persistence"]}
egui_extras = {path = "../egui/egui_extras"}#, features = ["image"]}
egui_file = {path = "../egui_file"}
gdal = {git = "https://github.com/georust/gdal.git"}

[profile.release]
strip = "symbols"

[profile.dev]
# opt-level = 1
