[package]
authors = ["Barugon"]
description = "VFR Flight Planner"
edition = "2021"
license = "GPL-3.0-or-later"
name = "fp_app"
version = "0.1.0"

[dependencies]
dirs = "4.0"
eframe = {version = "0.19", features = ["persistence", "wgpu"]}
egui_extras = {version = "0.19"}#, features = ["image"]}
egui_file = "0.2"
gdal = {git = "https://github.com/georust/gdal.git"}

[profile.release]
strip = "symbols"

[profile.dev]
# opt-level = 1
