[package]
authors = ["Barugon"]
description = "VFR Flight Planner"
edition = "2021"
license = "GPL-3.0-or-later"
name = "aviate"
version = "0.1.0"

[features]
mobile = []

[dependencies]
dirs = "5.0"
eframe = "0.27"
egui_extras = {version = "0.27", features = ["image"]}
egui_file = "0.17"
gdal = {version = "0.16", features = ["bindgen"]}
image = {version = "0.25", features = ["png"]}
rstar = "0.12"
serde_json = "1.0"

[profile.release]
strip = "symbols"
